<?php


/**
 * Implements hook_menu().
 */
function custom_menu() {
  $items = array();
  //$path = drupal_get_path('module', 'custom');
  //dsm($path);exit;

  // Define callback for menu structure callback.
  

  // $items['admin/config/user-interface/coffee'] = array(
  //   'title' => 'Coffee',
  //   'description' => 'Configuration for the Coffee module.',
  //   'page callback' => 'drupal_get_form',
  //   'page arguments' => array('coffee_admin_settings'),
  //   'access arguments' => array('administer coffee'),
  //   'type' => MENU_NORMAL_ITEM,
  //   'file' => 'coffee.admin.inc',
  //   'file path' => $path,
  // );

  // return $items;
}
